insert into category (name) values ('Glass & Glazing');
insert into category (name) values ('Epoxy Flooring');
insert into category (name) values ('Roofing (Asphalt)');
insert into category (name) values ('Termite Control');
insert into category (name) values ('RF Shielding');
insert into category (name) values ('Granite Surfaces');
insert into category (name) values ('Fire Protection');
insert into category (name) values ('Temp Fencing, Decorative Fencing and Gates');
insert into category (name) values ('Framing (Steel)');
insert into category (name) values ('Elevator');
