insert into organisation (contacts, description, rating, id) values ('756-895-3670', 'Lumbar spina bifida with hydrocephalus', 4.9, 1);
insert into organisation (contacts, description, rating, id) values ('674-243-9969', 'Nonspecific low blood-pressure reading', 2.8, 2);
insert into organisation (contacts, description, rating, id) values ('283-804-9427', 'Conjoined twin pregnancy, unspecified trimester', 3.2, 3);
insert into organisation (contacts, description, rating, id) values ('819-333-2154', 'Other fracture of shaft of ulna', 3.0, 4);
insert into organisation (contacts, description, rating, id) values ('248-459-4584', 'Other injury due to other accident to passenger ship, initial encounter', 1.4, 5);
insert into organisation (contacts, description, rating, id) values ('535-846-9789', 'Other superficial bite of unspecified forearm, subsequent encounter', 1.5, 6);
insert into organisation (contacts, description, rating, id) values ('376-838-9322', 'Traumatic rupture of palmar ligament of right ring finger at metacarpophalangeal and interphalangeal joint', 2.3, 7);
insert into organisation (contacts, description, rating, id) values ('795-285-2408', 'Open bite, unspecified elbow, subsequent encounter', 3.1, 8);
insert into organisation (contacts, description, rating, id) values ('586-812-8224', 'Assault by other hot objects, subsequent encounter', 2.3, 9);
insert into organisation (contacts, description, rating, id) values ('106-644-1002', 'Displaced supracondylar fracture without intracondylar extension of lower end of right femur, subsequent encounter for closed fracture with delayed healing', 1.1, 10);
insert into organisation (contacts, description, rating, id) values ('565-707-9507', 'Separation of muscle (nontraumatic), right ankle and foot', 1.2, 11);
insert into organisation (contacts, description, rating, id) values ('531-139-4771', 'Injury of musculocutaneous nerve, unspecified arm, initial encounter', 4.1, 12);
insert into organisation (contacts, description, rating, id) values ('450-256-8012', 'Burn of first degree of multiple sites of right lower limb, except ankle and foot', 2.5, 13);
insert into organisation (contacts, description, rating, id) values ('794-537-1086', 'Glaucoma secondary to eye inflammation, left eye, severe stage', 3.8, 14);
insert into organisation (contacts, description, rating, id) values ('206-963-7011', 'Displaced fracture of olecranon process without intraarticular extension of left ulna', 1.8, 15);
insert into organisation (contacts, description, rating, id) values ('804-824-5746', 'Burn of unspecified degree of left ear [any part, except ear drum]', 3.8, 16);
insert into organisation (contacts, description, rating, id) values ('176-807-2627', 'Displaced fracture of anterior process of unspecified calcaneus', 3.8, 17);
insert into organisation (contacts, description, rating, id) values ('101-159-9632', 'Unspecified fracture of third metacarpal bone, right hand, sequela', 1.2, 18);
insert into organisation (contacts, description, rating, id) values ('845-976-7465', 'Salter-Harris Type I physeal fracture of lower end of ulna, unspecified arm, subsequent encounter for fracture with routine healing', 1.5, 19);
insert into organisation (contacts, description, rating, id) values ('605-108-4922', '2-part displaced fracture of surgical neck of left humerus', 2.5, 20);
insert into organisation (contacts, description, rating, id) values ('359-662-5068', 'Other sprain of right thumb, sequela', 3.7, 21);
insert into organisation (contacts, description, rating, id) values ('265-502-5773', 'Laceration without foreign body of unspecified ear', 1.6, 22);
insert into organisation (contacts, description, rating, id) values ('221-971-7839', 'Other specified injury of superficial vein at shoulder and upper arm level, right arm, sequela', 4.9, 23);
insert into organisation (contacts, description, rating, id) values ('850-354-8654', 'Fracture of unspecified phalanx of right ring finger, subsequent encounter for fracture with malunion', 4.5, 24);
insert into organisation (contacts, description, rating, id) values ('295-565-7065', 'Pre-existing essential hypertension complicating pregnancy, unspecified trimester', 2.8, 25);
insert into organisation (contacts, description, rating, id) values ('599-442-1012', 'Burn of first degree of left axilla', 3.5, 26);
insert into organisation (contacts, description, rating, id) values ('715-876-6628', 'Nondisplaced Zone II fracture of sacrum, initial encounter for closed fracture', 3.6, 27);
insert into organisation (contacts, description, rating, id) values ('636-716-6809', 'Neuronal ceroid lipofuscinosis', 3.5, 28);
insert into organisation (contacts, description, rating, id) values ('670-176-7095', 'Anaphylactic reaction due to eggs, sequela', 4.2, 29);
insert into organisation (contacts, description, rating, id) values ('308-893-7805', 'Poisoning by, adverse effect of and underdosing of other and unspecified psychodysleptics [hallucinogens]', 4.4, 30);
insert into organisation (contacts, description, rating, id) values ('171-184-7451', 'Perforation due to foreign body accidentally left in body following unspecified procedure, initial encounter', 2.3, 31);
insert into organisation (contacts, description, rating, id) values ('372-472-3208', 'Brown''s sheath syndrome', 4.9, 32);
insert into organisation (contacts, description, rating, id) values ('644-621-5944', 'Underdosing of cardiac-stimulant glycosides and drugs of similar action, sequela', 3.7, 33);
insert into organisation (contacts, description, rating, id) values ('342-997-5791', 'Legal intervention involving injury by tear gas, bystander injured, subsequent encounter', 3.6, 34);
insert into organisation (contacts, description, rating, id) values ('836-691-5849', 'Pathological dislocation of hip, not elsewhere classified', 3.6, 35);
insert into organisation (contacts, description, rating, id) values ('443-998-2131', 'Unspecified physeal fracture of lower end of right fibula, subsequent encounter for fracture with routine healing', 4.9, 36);
insert into organisation (contacts, description, rating, id) values ('750-942-6442', 'Neonatal aspiration of (clear) amniotic fluid and mucus with respiratory symptoms', 1.2, 37);
insert into organisation (contacts, description, rating, id) values ('321-699-7129', 'Injury of musculocutaneous nerve, right arm, initial encounter', 3.5, 38);
insert into organisation (contacts, description, rating, id) values ('548-127-7886', 'Behcet''s disease', 3.3, 39);
insert into organisation (contacts, description, rating, id) values ('572-856-4796', 'Person boarding or alighting a heavy transport vehicle injured in noncollision transport accident, sequela', 3.7, 40);
insert into organisation (contacts, description, rating, id) values ('344-651-6848', 'Acute leukemia of unspecified cell type not having achieved remission', 4.3, 41);
insert into organisation (contacts, description, rating, id) values ('666-219-2721', 'Other chorioretinal scars, bilateral', 2.4, 42);
insert into organisation (contacts, description, rating, id) values ('240-996-6368', 'Poisoning by, adverse effect of and underdosing of other and unspecified general anesthetics', 3.5, 43);
insert into organisation (contacts, description, rating, id) values ('234-606-1056', 'Activity, roller skating (inline) and skateboarding', 3.7, 44);
insert into organisation (contacts, description, rating, id) values ('117-130-1241', 'Traumatic rupture of lumbar intervertebral disc, subsequent encounter', 2.9, 45);
insert into organisation (contacts, description, rating, id) values ('571-304-6350', 'Jumping or diving into other water striking wall causing other injury, subsequent encounter', 3.8, 46);
insert into organisation (contacts, description, rating, id) values ('134-125-8742', 'Salter-Harris Type I physeal fracture of upper end of right tibia, subsequent encounter for fracture with routine healing', 1.2, 47);
insert into organisation (contacts, description, rating, id) values ('962-176-9902', 'Underdosing of anticoagulant antagonist, vitamin K and other coagulants, subsequent encounter', 3.4, 48);
insert into organisation (contacts, description, rating, id) values ('746-812-5869', 'Open bite of right breast, sequela', 2.0, 49);
insert into organisation (contacts, description, rating, id) values ('939-663-8156', 'Nondisplaced fracture of posterior process of right talus, initial encounter for closed fracture', 2.0, 50);
insert into organisation (contacts, description, rating, id) values ('849-684-9370', 'Blister (nonthermal) of breast, unspecified breast, sequela', 4.4, 51);
insert into organisation (contacts, description, rating, id) values ('560-742-2843', 'Poisoning by enzymes, accidental (unintentional), initial encounter', 4.1, 52);
insert into organisation (contacts, description, rating, id) values ('864-465-2046', 'Osteophyte, unspecified hip', 4.3, 53);
insert into organisation (contacts, description, rating, id) values ('633-545-6706', 'Burn of unspecified degree of unspecified lower leg', 4.8, 54);
insert into organisation (contacts, description, rating, id) values ('791-171-0530', 'Salter-Harris Type I physeal fracture of lower end of right tibia, sequela', 2.4, 55);
insert into organisation (contacts, description, rating, id) values ('139-986-1837', 'Malignant neoplasm of pancreas, unspecified', 3.2, 56);
insert into organisation (contacts, description, rating, id) values ('969-587-2414', 'Chronic sinusitis', 4.4, 57);
insert into organisation (contacts, description, rating, id) values ('399-950-8682', 'Poisoning by, adverse effect of and underdosing of antivaricose drugs, including sclerosing agents', 2.7, 58);
insert into organisation (contacts, description, rating, id) values ('668-199-1664', 'Person boarding or alighting a three-wheeled motor vehicle injured in collision with fixed or stationary object, sequela', 1.7, 59);
insert into organisation (contacts, description, rating, id) values ('948-581-3005', 'Noninfective disorders of pinna, unspecified ear', 2.1, 60);
insert into organisation (contacts, description, rating, id) values ('427-560-7993', 'Maxillary fracture, right side, subsequent encounter for fracture with delayed healing', 3.3, 61);
insert into organisation (contacts, description, rating, id) values ('438-903-7796', 'Unspecified injury of muscle, fascia and tendon of other parts of biceps, unspecified arm, initial encounter', 4.2, 62);
insert into organisation (contacts, description, rating, id) values ('844-374-1237', 'Salter-Harris Type I physeal fracture of upper end of unspecified fibula', 2.4, 63);
insert into organisation (contacts, description, rating, id) values ('724-162-6510', 'Laceration of other specified muscles, fascia and tendons at thigh level, unspecified thigh, initial encounter', 1.6, 64);
insert into organisation (contacts, description, rating, id) values ('904-563-9328', 'Other specific joint derangements of shoulder, not elsewhere classified', 3.9, 65);
insert into organisation (contacts, description, rating, id) values ('871-681-3939', 'Sprain of interphalangeal joint of left ring finger, initial encounter', 1.3, 66);
insert into organisation (contacts, description, rating, id) values ('247-241-0094', 'Hypoxic ischemic encephalopathy [HIE], unspecified', 1.2, 67);
insert into organisation (contacts, description, rating, id) values ('301-189-9455', 'Cholesteatoma of attic, left ear', 1.6, 68);
insert into organisation (contacts, description, rating, id) values ('543-557-8298', 'Displaced oblique fracture of shaft of left femur, subsequent encounter for open fracture type I or II with malunion', 1.9, 69);
insert into organisation (contacts, description, rating, id) values ('829-442-4111', 'Toxic effect of ethanol, accidental (unintentional)', 4.3, 70);
insert into organisation (contacts, description, rating, id) values ('887-721-9031', 'Displacement of ventricular intracranial (communicating) shunt, subsequent encounter', 4.5, 71);
insert into organisation (contacts, description, rating, id) values ('847-465-8984', 'Unspecified complication of anesthesia during pregnancy, third trimester', 2.3, 72);
insert into organisation (contacts, description, rating, id) values ('947-318-3638', 'Poisoning by thyroid hormones and substitutes, accidental (unintentional), sequela', 2.0, 73);
insert into organisation (contacts, description, rating, id) values ('846-187-0715', 'Human immunodeficiency virus [HIV] disease', 1.1, 74);
insert into organisation (contacts, description, rating, id) values ('708-601-4247', 'Laceration of other blood vessels at wrist and hand level of right arm, initial encounter', 4.1, 75);
insert into organisation (contacts, description, rating, id) values ('702-988-9137', 'Passenger in three-wheeled motor vehicle injured in collision with railway train or railway vehicle in traffic accident, sequela', 2.2, 76);
insert into organisation (contacts, description, rating, id) values ('571-184-4847', 'Fear of injury', 4.8, 77);
insert into organisation (contacts, description, rating, id) values ('941-327-9145', 'Epidural hemorrhage with loss of consciousness of unspecified duration, subsequent encounter', 3.7, 78);
insert into organisation (contacts, description, rating, id) values ('814-823-5343', 'Non-pressure chronic ulcer of unspecified part of right lower leg with unspecified severity', 1.1, 79);
insert into organisation (contacts, description, rating, id) values ('180-374-2871', 'Other rupture of muscle (nontraumatic), unspecified lower leg', 2.4, 80);
insert into organisation (contacts, description, rating, id) values ('479-400-4377', 'Barton''s fracture of right radius, subsequent encounter for open fracture type I or II with malunion', 2.2, 81);
insert into organisation (contacts, description, rating, id) values ('431-920-9185', 'Contusion and laceration of left cerebrum with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness', 2.6, 82);
insert into organisation (contacts, description, rating, id) values ('143-243-9398', 'Displaced spiral fracture of shaft of unspecified tibia, subsequent encounter for closed fracture with routine healing', 2.9, 83);
insert into organisation (contacts, description, rating, id) values ('641-726-4129', 'Activity, mountain climbing, rock climbing and wall climbing', 1.9, 84);
insert into organisation (contacts, description, rating, id) values ('542-340-8946', 'Unspecified open wound of left front wall of thorax with penetration into thoracic cavity, subsequent encounter', 4.1, 85);
insert into organisation (contacts, description, rating, id) values ('489-886-0584', 'Atherosclerosis of autologous vein bypass graft(s) of the extremities with intermittent claudication, bilateral legs', 1.1, 86);
insert into organisation (contacts, description, rating, id) values ('903-160-3365', 'Nondisplaced fracture of medial cuneiform of unspecified foot, subsequent encounter for fracture with malunion', 4.5, 87);
insert into organisation (contacts, description, rating, id) values ('302-271-3179', 'Long term (current) use of systemic steroids', 4.4, 88);
insert into organisation (contacts, description, rating, id) values ('151-764-5440', 'Displaced bicondylar fracture of left tibia', 4.3, 89);
insert into organisation (contacts, description, rating, id) values ('782-745-6503', 'Vulvovaginal ulceration and inflammation in diseases classified elsewhere', 1.9, 90);
insert into organisation (contacts, description, rating, id) values ('805-941-7211', 'Displaced fracture of distal phalanx of left thumb, initial encounter for open fracture', 2.1, 91);
insert into organisation (contacts, description, rating, id) values ('171-641-4906', 'Pedal cycle driver injured in collision with other nonmotor vehicle in nontraffic accident, sequela', 4.7, 92);
insert into organisation (contacts, description, rating, id) values ('278-155-4186', 'Pedal cycle driver injured in collision with other nonmotor vehicle in nontraffic accident, initial encounter', 1.4, 93);
insert into organisation (contacts, description, rating, id) values ('615-181-9653', 'Chronic myringitis, right ear', 3.4, 94);
insert into organisation (contacts, description, rating, id) values ('700-504-9140', 'Monocular esotropia, right eye', 3.5, 95);
insert into organisation (contacts, description, rating, id) values ('580-293-0757', 'Drug-induced interstitial lung disorders, unspecified', 4.6, 96);
insert into organisation (contacts, description, rating, id) values ('243-311-2441', 'Toxic effect of phenol and phenol homologues, intentional self-harm', 3.6, 97);
insert into organisation (contacts, description, rating, id) values ('984-202-6764', 'Post-traumatic urethral stricture, male', 2.0, 98);
insert into organisation (contacts, description, rating, id) values ('262-742-2495', 'Age-related osteoporosis with current pathological fracture, forearm', 2.4, 99);
insert into organisation (contacts, description, rating, id) values ('358-940-2374', 'Unspecified iridocyclitis', 1.7, 100);
